package com.blobcity

import android.os.Environment

class Constant {
    companion object {
                            /**assetPath**/
        val assetTopicOnePath = "output/Test_Course/topic-one/"
        val assetBasic394Path: String = assetTopicOnePath+"basic-394"
        val assetBasic395Path: String = assetTopicOnePath+"basic-395"
        val assetBasic396Path: String = assetTopicOnePath+"basic-396"
        val assetBasic397Path: String = assetTopicOnePath+"basic-397"
        val assetBasic408Path: String = assetTopicOnePath+"basic-408"
        val assetBasic409Path: String = assetTopicOnePath+"basic-409"
        val assetBasic550Path: String = assetTopicOnePath+"basic-550"
        val assetBasic1421Path: String = assetTopicOnePath+"basic-1421"
        val assetBasic1422Path: String = assetTopicOnePath+"basic-1422"
        val assetAdvanced398Path: String = assetTopicOnePath+"advanced-398"
        val assetAdvanced399Path: String = assetTopicOnePath+"advanced-399"
        val assetAdvanced403Path: String = assetTopicOnePath+"advanced-403"
        val assetAdvanced404Path: String = assetTopicOnePath+"advanced-404"
        val assetAdvanced1429Path: String = assetTopicOnePath+"advanced-1429"
        val assetAdvanced1430Path: String = assetTopicOnePath+"advanced-1430"
        val assetAdvanced1431Path: String = assetTopicOnePath+"advanced-1431"
        val assetAdvanced1432Path: String = assetTopicOnePath+"advanced-1432"
        val assetIntermediate400Path: String = assetTopicOnePath+"intermediate-400"
        val assetIntermediate401Path: String = assetTopicOnePath+"intermediate-401"
        val assetIntermediate402Path: String = assetTopicOnePath+"intermediate-402"
        val assetIntermediate405Path: String = assetTopicOnePath+"intermediate-405"
        val assetIntermediate413Path: String = assetTopicOnePath+"intermediate-413"
        val assetIntermediate549Path: String = assetTopicOnePath+"intermediate-549"
        val assetIntermediate1426Path: String = assetTopicOnePath+"intermediate-1426"
        val assetIntermediate1427Path: String = assetTopicOnePath+"intermediate-1427"
        val assetIntermediate1428Path: String = assetTopicOnePath+"intermediate-1428"

        val assetTopicTwoPath: String = "output/Test_Course/topic-two/"
        val assetBasic406Path: String = assetTopicTwoPath+"basic-406"
        val assetBasic407Path: String = assetTopicTwoPath+"basic-407"
        val assetBasic1423Path: String = assetTopicTwoPath+"basic-1423"
        val assetBasic1424Path: String = assetTopicTwoPath+"basic-1424"
        val assetAdvanced410Path: String = assetTopicTwoPath+"advanced-410"
        val assetAdvanced411Path: String = assetTopicTwoPath+"advanced-411"
        val assetAdvanced415Path: String = assetTopicTwoPath+"advanced-415"
        val assetAdvanced416Path: String = assetTopicTwoPath+"advanced-416"
        val assetIntermediate412Path: String = assetTopicTwoPath+"intermediate-412"
        val assetIntermediate414Path: String = assetTopicTwoPath+"intermediate-414"
        val assetIntermediate417Path: String = assetTopicTwoPath+"intermediate-417"
        val assetIntermediate1425Path: String = assetTopicTwoPath+"intermediate-1425"

        val assetTopicThreePath: String = "output/Test_Course/topic-three/"
        val assetBasic418Path: String = assetTopicThreePath+"basic-418"
        val assetBasic419Path: String = assetTopicThreePath+"basic-419"
        val assetBasic420Path: String = assetTopicThreePath+"basic-420"
        val assetBasic421Path: String = assetTopicThreePath+"basic-421"
        val assetAdvanced422Path: String = assetTopicThreePath+"advanced-422"
        val assetAdvanced423Path: String = assetTopicThreePath+"advanced-423"
        val assetAdvanced427Path: String = assetTopicThreePath+"advanced-427"
        val assetAdvanced428Path: String = assetTopicThreePath+"advanced-428"
        val assetIntermediate424Path: String = assetTopicThreePath+"intermediate-424"
        val assetIntermediate425Path: String = assetTopicThreePath+"intermediate-425"
        val assetIntermediate426Path: String = assetTopicThreePath+"intermediate-426"
        val assetIntermediate429Path: String = assetTopicThreePath+"intermediate-429"

        val assetTopicFourPath: String = "output/Test_Course/topic-four/"
        val assetBasic430Path: String = assetTopicFourPath+"basic-430"
        val assetBasic431Path: String = assetTopicFourPath+"basic-431"
        val assetBasic432Path: String = assetTopicFourPath+"basic-432"
        val assetBasic433Path: String = assetTopicFourPath+"basic-433"
        val assetAdvanced434Path: String = assetTopicFourPath+"advanced-434"
        val assetAdvanced435Path: String = assetTopicFourPath+"advanced-435"
        val assetAdvanced439Path: String = assetTopicFourPath+"advanced-439"
        val assetAdvanced440Path: String = assetTopicFourPath+"advanced-440"
        val assetIntermediate436Path: String = assetTopicFourPath+"intermediate-436"
        val assetIntermediate437Path: String = assetTopicFourPath+"intermediate-437"
        val assetIntermediate438Path: String = assetTopicFourPath+"intermediate-438"
        val assetIntermediate441Path: String = assetTopicFourPath+"intermediate-441"

        val assetTopicFivePath: String = "output/Test_Course/topic-five/"
        val assetBasic442Path: String = assetTopicFivePath+"basic-442"
        val assetBasic443Path: String = assetTopicFivePath+"basic-443"
        val assetBasic444Path: String = assetTopicFivePath+"basic-444"
        val assetBasic445Path: String = assetTopicFivePath+"basic-445"
        val assetAdvanced446Path: String = assetTopicFivePath+"advanced-446"
        val assetAdvanced447Path: String = assetTopicFivePath+"advanced-447"
        val assetAdvanced451Path: String = assetTopicFivePath+"advanced-451"
        val assetAdvanced452Path: String = assetTopicFivePath+"advanced-452"
        val assetIntermediate448Path: String = assetTopicFivePath+"intermediate-448"
        val assetIntermediate449Path: String = assetTopicFivePath+"intermediate-449"
        val assetIntermediate450Path: String = assetTopicFivePath+"intermediate-450"
        val assetIntermediate453Path: String = assetTopicFivePath+"intermediate-453"

        val assetTopicSixPath: String = "output/Test_Course/topic-six/"
        val assetBasic454Path: String = assetTopicSixPath+"basic-454"
        val assetBasic455Path: String = assetTopicSixPath+"basic-455"
        val assetBasic456Path: String = assetTopicSixPath+"basic-456"
        val assetBasic457Path: String = assetTopicSixPath+"basic-457"
        val assetAdvanced458Path: String = assetTopicSixPath+"advanced-458"
        val assetAdvanced459Path: String = assetTopicSixPath+"advanced-459"
        val assetAdvanced463Path: String = assetTopicSixPath+"advanced-463"
        val assetAdvanced464Path: String = assetTopicSixPath+"advanced-464"
        val assetIntermediate460Path: String = assetTopicSixPath+"intermediate-460"
        val assetIntermediate461Path: String = assetTopicSixPath+"intermediate-461"
        val assetIntermediate462Path: String = assetTopicSixPath+"intermediate-462"
        val assetIntermediate465Path: String = assetTopicSixPath+"intermediate-465"

        val assetTopicSevenPath: String = "output/Test_Course/topic-seven/"
        val assetBasic466Path: String = assetTopicSevenPath+"basic-466"
        val assetBasic467Path: String = assetTopicSevenPath+"basic-467"
        val assetBasic468Path: String = assetTopicSevenPath+"basic-468"
        val assetBasic469Path: String = assetTopicSevenPath+"basic-469"
        val assetAdvanced470Path: String = assetTopicSevenPath+"advanced-470"
        val assetAdvanced471Path: String = assetTopicSevenPath+"advanced-471"
        val assetAdvanced475Path: String = assetTopicSevenPath+"advanced-475"
        val assetAdvanced476Path: String = assetTopicSevenPath+"advanced-476"
        val assetIntermediate472Path: String = assetTopicSevenPath+"intermediate-472"
        val assetIntermediate473Path: String = assetTopicSevenPath+"intermediate-473"
        val assetIntermediate474Path: String = assetTopicSevenPath+"intermediate-474"
        val assetIntermediate477Path: String = assetTopicSevenPath+"intermediate-477"

        val assetTopicEightPath: String = "output/Test_Course/topic-eight/"
        val assetBasic478Path: String = assetTopicEightPath+"basic-478"
        val assetBasic479Path: String = assetTopicEightPath+"basic-479"
        val assetBasic480Path: String = assetTopicEightPath+"basic-480"
        val assetBasic481Path: String = assetTopicEightPath+"basic-481"
        val assetAdvanced482Path: String = assetTopicEightPath+"advanced-482"
        val assetAdvanced483Path: String = assetTopicEightPath+"advanced-483"
        val assetAdvanced487Path: String = assetTopicEightPath+"advanced-487"
        val assetAdvanced488Path: String = assetTopicEightPath+"advanced-488"
        val assetIntermediate484Path: String = assetTopicEightPath+"intermediate-484"
        val assetIntermediate485Path: String = assetTopicEightPath+"intermediate-485"
        val assetIntermediate486Path: String = assetTopicEightPath+"intermediate-486"
        val assetIntermediate489Path: String = assetTopicEightPath+"intermediate-489"

        val assetTopicNinePath: String = "output/Test_Course/topic-nine/"
        val assetBasic490Path: String = assetTopicNinePath+"basic-490"
        val assetBasic491Path: String = assetTopicNinePath+"basic-491"
        val assetBasic492Path: String = assetTopicNinePath+"basic-492"
        val assetBasic493Path: String = assetTopicNinePath+"basic-493"
        val assetAdvanced494Path: String = assetTopicNinePath+"advanced-494"
        val assetAdvanced495Path: String = assetTopicNinePath+"advanced-495"
        val assetAdvanced499Path: String = assetTopicNinePath+"advanced-499"
        val assetAdvanced500Path: String = assetTopicNinePath+"advanced-500"
        val assetIntermediate496Path: String = assetTopicNinePath+"intermediate-496"
        val assetIntermediate497Path: String = assetTopicNinePath+"intermediate-497"
        val assetIntermediate498Path: String = assetTopicNinePath+"intermediate-498"
        val assetIntermediate501Path: String = assetTopicNinePath+"intermediate-501"


                            /**localPath**/

        val localPath: String = Environment.getExternalStorageDirectory()
                                .absolutePath
        val localOutputPath: String = localPath+"/blobcity"
        val localTestCoursePath: String = localOutputPath+"/Test_Course"

        val localTopicOnePath: String = localTestCoursePath+"/topic-one"
        val localBasic394Path: String = localTopicOnePath+"/basic-394/"
        val localBasic395Path: String = localTopicOnePath+"/basic-395/"
        val localBasic396Path: String = localTopicOnePath+"/basic-396/"
        val localBasic397Path: String = localTopicOnePath+"/basic-397/"
        val localBasic408Path: String = localTopicOnePath+"/basic-408/"
        val localBasic409Path: String = localTopicOnePath+"/basic-409/"
        val localBasic550Path: String = localTopicOnePath+"/basic-550/"
        val localBasic1421Path: String = localTopicOnePath+"/basic-1421/"
        val localBasic1422Path: String = localTopicOnePath+"/basic-1422/"
        val localAdvanced398Path: String = localTopicOnePath+"/advanced-398/"
        val localAdvanced399Path: String = localTopicOnePath+"/advanced-399/"
        val localAdvanced403Path: String = localTopicOnePath+"/advanced-403/"
        val localAdvanced404Path: String = localTopicOnePath+"/advanced-404/"
        val localAdvanced1429Path: String = localTopicOnePath+"/advanced-1429/"
        val localAdvanced1430Path: String = localTopicOnePath+"/advanced-1430/"
        val localAdvanced1431Path: String = localTopicOnePath+"/advanced-1431/"
        val localAdvanced1432Path: String = localTopicOnePath+"/advanced-1432/"
        val localIntermediate400Path: String = localTopicOnePath+"/intermediate-400/"
        val localIntermediate401Path: String = localTopicOnePath+"/intermediate-401/"
        val localIntermediate402Path: String = localTopicOnePath+"/intermediate-402/"
        val localIntermediate405Path: String = localTopicOnePath+"/intermediate-405/"
        val localIntermediate413Path: String = localTopicOnePath+"/intermediate-413/"
        val localIntermediate549Path: String = localTopicOnePath+"/intermediate-549/"
        val localIntermediate1426Path: String = localTopicOnePath+"/intermediate-1426/"
        val localIntermediate1427Path: String = localTopicOnePath+"/intermediate-1427/"
        val localIntermediate1428Path: String = localTopicOnePath+"/intermediate-1428/"

        val localTopicTwoPath: String = localTestCoursePath+"/topic-two"
        val localBasic406Path: String = localTopicTwoPath+"/basic-406/"
        val localBasic407Path: String = localTopicTwoPath+"/basic-407/"
        val localBasic1423Path: String = localTopicTwoPath+"/basic-1423/"
        val localBasic1424Path: String = localTopicTwoPath+"/basic-1424/"
        val localAdvanced410Path: String = localTopicTwoPath+"/advanced-410/"
        val localAdvanced411Path: String = localTopicTwoPath+"/advanced-411/"
        val localAdvanced415Path: String = localTopicTwoPath+"/advanced-415/"
        val localAdvanced416Path: String = localTopicTwoPath+"/advanced-416/"
        val localIntermediate412Path: String = localTopicTwoPath+"/intermediate-412/"
        val localIntermediate414Path: String = localTopicTwoPath+"/intermediate-414/"
        val localIntermediate417Path: String = localTopicTwoPath+"/intermediate-417/"
        val localIntermediate1425Path: String = localTopicTwoPath+"/intermediate-1425/"

        val localTopicThreePath: String = localTestCoursePath+"/topic-three"
        val localBasic418Path: String = localTopicThreePath+"/basic-418/"
        val localBasic419Path: String = localTopicThreePath+"/basic-419/"
        val localBasic420Path: String = localTopicThreePath+"/basic-420/"
        val localBasic421Path: String = localTopicThreePath+"/basic-421/"
        val localAdvanced422Path: String = localTopicThreePath+"/advanced-422/"
        val localAdvanced423Path: String = localTopicThreePath+"/advanced-423/"
        val localAdvanced427Path: String = localTopicThreePath+"/advanced-427/"
        val localAdvanced428Path: String = localTopicThreePath+"/advanced-428/"
        val localIntermediate424Path: String = localTopicThreePath+"/intermediate-424/"
        val localIntermediate425Path: String = localTopicThreePath+"/intermediate-424/"
        val localIntermediate426Path: String = localTopicThreePath+"/intermediate-426/"
        val localIntermediate429Path: String = localTopicThreePath+"/intermediate-429/"

        val localTopicFourPath: String = localTestCoursePath+"/topic-four"
        val localBasic430Path: String = localTopicFourPath+"/basic-430/"
        val localBasic431Path: String = localTopicFourPath+"/basic-431/"
        val localBasic432Path: String = localTopicFourPath+"/basic-432/"
        val localBasic433Path: String = localTopicFourPath+"/basic-433/"
        val localAdvanced434Path: String = localTopicFourPath+"/advanced-434/"
        val localAdvanced435Path: String = localTopicFourPath+"/advanced-435/"
        val localAdvanced439Path: String = localTopicFourPath+"/advanced-439/"
        val localAdvanced440Path: String = localTopicFourPath+"/advanced-440/"
        val localIntermediate436Path: String = localTopicFourPath+"/intermediate-436/"
        val localIntermediate437Path: String = localTopicFourPath+"/intermediate-437/"
        val localIntermediate438Path: String = localTopicFourPath+"/intermediate-438/"
        val localIntermediate441Path: String = localTopicFourPath+"/intermediate-441/"

        val localTopicFivePath: String = localTestCoursePath+"/topic-five"
        val localBasic442Path: String = localTopicFivePath+"/basic-442/"
        val localBasic443Path: String = localTopicFivePath+"/basic-443/"
        val localBasic444Path: String = localTopicFivePath+"/basic-444/"
        val localBasic445Path: String = localTopicFivePath+"/basic-445/"
        val localAdvanced446Path: String = localTopicFivePath+"/advanced-446/"
        val localAdvanced447Path: String = localTopicFivePath+"/advanced-447/"
        val localAdvanced451Path: String = localTopicFivePath+"/advanced-451/"
        val localAdvanced452Path: String = localTopicFivePath+"/advanced-452/"
        val localIntermediate448Path: String = localTopicFivePath+"/intermediate-448/"
        val localIntermediate449Path: String = localTopicFivePath+"/intermediate-449/"
        val localIntermediate450Path: String = localTopicFivePath+"/intermediate-450/"
        val localIntermediate453Path: String = localTopicFivePath+"/intermediate-453/"

        val localTopicSixPath: String = localTestCoursePath+"/topic-six"
        val localBasic454Path: String = localTopicSixPath+"/basic-454/"
        val localBasic455Path: String = localTopicSixPath+"/basic-455/"
        val localBasic456Path: String = localTopicSixPath+"/basic-456/"
        val localBasic457Path: String = localTopicSixPath+"/basic-457/"
        val localAdvanced458Path: String = localTopicSixPath+"/advanced-458/"
        val localAdvanced459Path: String = localTopicSixPath+"/advanced-459/"
        val localAdvanced463Path: String = localTopicSixPath+"/advanced-463/"
        val localAdvanced464Path: String = localTopicSixPath+"/advanced-464/"
        val localIntermediate460Path: String = localTopicSixPath+"/intermediate-460/"
        val localIntermediate461Path: String = localTopicSixPath+"/intermediate-461/"
        val localIntermediate462Path: String = localTopicSixPath+"/intermediate-462/"
        val localIntermediate465Path: String = localTopicSixPath+"/intermediate-465/"

        val localTopicSevenPath: String = localTestCoursePath+"/topic-seven"
        val localBasic466Path: String = localTopicSevenPath+"/basic-466/"
        val localBasic467Path: String = localTopicSevenPath+"/basic-467/"
        val localBasic468Path: String = localTopicSevenPath+"/basic-468/"
        val localBasic469Path: String = localTopicSevenPath+"/basic-469/"
        val localAdvanced470Path: String = localTopicSevenPath+"/advanced-470/"
        val localAdvanced471Path: String = localTopicSevenPath+"/advanced-471/"
        val localAdvanced475Path: String = localTopicSevenPath+"/advanced-475/"
        val localAdvanced476Path: String = localTopicSevenPath+"/advanced-476/"
        val localIntermediate472Path: String = localTopicSevenPath+"/intermediate-472/"
        val localIntermediate473Path: String = localTopicSevenPath+"/intermediate-473/"
        val localIntermediate474Path: String = localTopicSevenPath+"/intermediate-474/"
        val localIntermediate477Path: String = localTopicSevenPath+"/intermediate-477/"

        val localTopicEightPath: String = localTestCoursePath+"/topic-eight"
        val localBasic478Path: String = localTopicEightPath+"/basic-478/"
        val localBasic479Path: String = localTopicEightPath+"/basic-479/"
        val localBasic480Path: String = localTopicEightPath+"/basic-480/"
        val localBasic481Path: String = localTopicEightPath+"/basic-481/"
        val localAdvanced482Path: String = localTopicEightPath+"/advanced-482/"
        val localAdvanced483Path: String = localTopicEightPath+"/advanced-483/"
        val localAdvanced487Path: String = localTopicEightPath+"/advanced-487/"
        val localAdvanced488Path: String = localTopicEightPath+"/advanced-488/"
        val localIntermediate484Path: String = localTopicEightPath+"/intermediate-484/"
        val localIntermediate485Path: String = localTopicEightPath+"/intermediate-485/"
        val localIntermediate486Path: String = localTopicEightPath+"/intermediate-486/"
        val localIntermediate489Path: String = localTopicEightPath+"/intermediate-489/"

        val localTopicNinePath: String = localTestCoursePath+"/topic-nine"
        val localBasic490Path: String = localTopicNinePath+"/basic-490/"
        val localBasic491Path: String = localTopicNinePath+"/basic-491/"
        val localBasic492Path: String = localTopicNinePath+"/basic-492/"
        val localBasic493Path: String = localTopicNinePath+"/basic-493/"
        val localAdvanced494Path: String = localTopicNinePath+"/advanced-494/"
        val localAdvanced495Path: String = localTopicNinePath+"/advanced-495/"
        val localAdvanced499Path: String = localTopicNinePath+"/advanced-499/"
        val localAdvanced500Path: String = localTopicNinePath+"/advanced-500/"
        val localIntermediate496Path: String = localTopicNinePath+"/intermediate-496/"
        val localIntermediate497Path: String = localTopicNinePath+"/intermediate-497/"
        val localIntermediate498Path: String = localTopicNinePath+"/intermediate-498/"
        val localIntermediate501Path: String = localTopicNinePath+"/intermediate-501/"
    }
}