package com.blobcity

import android.os.Environment

class Constant {
    companion object {
                            /**assetPath**/
        val assetTopicOnePath = "output/Test_Course/topic-one/"
        val assetBasic394Path: String = assetTopicOnePath+"basic-394"
        val assetBasic395Path: String = assetTopicOnePath+"basic-395"
        val assetBasic396Path: String = assetTopicOnePath+"basic-396"
        val assetBasic397Path: String = assetTopicOnePath+"basic-397"
        val assetBasic408Path: String = assetTopicOnePath+"basic-408"
        val assetBasic409Path: String = assetTopicOnePath+"basic-409"
        val assetBasic550Path: String = assetTopicOnePath+"basic-550"
        val assetBasic1421Path: String = assetTopicOnePath+"basic-1421"
        val assetBasic1422Path: String = assetTopicOnePath+"basic-1422"
        val assetAdvanced398Path: String = assetTopicOnePath+"advanced-398"
        val assetAdvanced399Path: String = assetTopicOnePath+"advanced-399"
        val assetAdvanced403Path: String = assetTopicOnePath+"advanced-403"
        val assetAdvanced404Path: String = assetTopicOnePath+"advanced-404"
        val assetAdvanced1429Path: String = assetTopicOnePath+"advanced-1429"
        val assetAdvanced1430Path: String = assetTopicOnePath+"advanced-1430"
        val assetAdvanced1431Path: String = assetTopicOnePath+"advanced-1431"
        val assetAdvanced1432Path: String = assetTopicOnePath+"advanced-1432"
        val assetIntermediate400Path: String = assetTopicOnePath+"intermediate-400"
        val assetIntermediate401Path: String = assetTopicOnePath+"intermediate-401"
        val assetIntermediate402Path: String = assetTopicOnePath+"intermediate-402"
        val assetIntermediate405Path: String = assetTopicOnePath+"intermediate-405"
        val assetIntermediate413Path: String = assetTopicOnePath+"intermediate-413"
        val assetIntermediate549Path: String = assetTopicOnePath+"intermediate-549"
        val assetIntermediate1426Path: String = assetTopicOnePath+"intermediate-1426"
        val assetIntermediate1427Path: String = assetTopicOnePath+"intermediate-1427"
        val assetIntermediate1428Path: String = assetTopicOnePath+"intermediate-1428"

        val assetTopicTwoPath: String = "output/Test_Course/topic-two/"
        val assetBasic406Path: String = assetTopicTwoPath+"basic-406"
        val assetBasic407Path: String = assetTopicTwoPath+"basic-407"
        val assetBasic1423Path: String = assetTopicTwoPath+"basic-1423"
        val assetBasic1424Path: String = assetTopicTwoPath+"basic-1424"
        val assetAdvanced410Path: String = assetTopicTwoPath+"advanced-410"
        val assetAdvanced411Path: String = assetTopicTwoPath+"advanced-411"
        val assetAdvanced415Path: String = assetTopicTwoPath+"advanced-415"
        val assetAdvanced416Path: String = assetTopicTwoPath+"advanced-416"
        val assetIntermediate412Path: String = assetTopicTwoPath+"intermediate-412"
        val assetIntermediate414Path: String = assetTopicTwoPath+"intermediate-414"
        val assetIntermediate417Path: String = assetTopicTwoPath+"intermediate-417"
        val assetIntermediate1425Path: String = assetTopicTwoPath+"intermediate-1425"

        val assetTopicThreePath: String = "output/Test_Course/topic-three/"
        val assetBasic418Path: String = assetTopicThreePath+"basic-418"
        val assetBasic419Path: String = assetTopicThreePath+"basic-419"
        val assetBasic420Path: String = assetTopicThreePath+"basic-420"
        val assetBasic421Path: String = assetTopicThreePath+"basic-421"
        val assetAdvanced422Path: String = assetTopicThreePath+"advanced-422"
        val assetAdvanced423Path: String = assetTopicThreePath+"advanced-423"
        val assetAdvanced427Path: String = assetTopicThreePath+"advanced-427"
        val assetAdvanced428Path: String = assetTopicThreePath+"advanced-428"
        val assetIntermediate424Path: String = assetTopicThreePath+"intermediate-424"
        val assetIntermediate425Path: String = assetTopicThreePath+"intermediate-425"
        val assetIntermediate426Path: String = assetTopicThreePath+"intermediate-426"
        val assetIntermediate429Path: String = assetTopicThreePath+"intermediate-429"


                            /**localPath**/

        val localPath: String = Environment.getExternalStorageDirectory()
                                .absolutePath
        val localOutputPath: String = localPath+"/blobcity"
        val localTestCoursePath: String = localOutputPath+"/Test_Course"
        val localTopicOnePath: String = localTestCoursePath+"/topic-one"
        val localBasic394Path: String = localTopicOnePath+"/basic-394/"
        val localBasic395Path: String = localTopicOnePath+"/basic-395/"
        val localBasic396Path: String = localTopicOnePath+"/basic-396/"
        val localBasic397Path: String = localTopicOnePath+"/basic-397/"
        val localBasic408Path: String = localTopicOnePath+"/basic-408/"
        val localBasic409Path: String = localTopicOnePath+"/basic-409/"
        val localBasic550Path: String = localTopicOnePath+"/basic-550/"
        val localBasic1421Path: String = localTopicOnePath+"/basic-1421/"
        val localBasic1422Path: String = localTopicOnePath+"/basic-1422/"
        val localAdvanced398Path: String = localTopicOnePath+"/advanced-398/"
        val localAdvanced399Path: String = localTopicOnePath+"/advanced-399/"
        val localAdvanced403Path: String = localTopicOnePath+"/advanced-403/"
        val localAdvanced404Path: String = localTopicOnePath+"/advanced-404/"
        val localAdvanced1429Path: String = localTopicOnePath+"/advanced-1429/"
        val localAdvanced1430Path: String = localTopicOnePath+"/advanced-1430/"
        val localAdvanced1431Path: String = localTopicOnePath+"/advanced-1431/"
        val localAdvanced1432Path: String = localTopicOnePath+"/advanced-1432/"
        val localIntermediate400Path: String = localTopicOnePath+"/intermediate-400/"
        val localIntermediate401Path: String = localTopicOnePath+"/intermediate-401/"
        val localIntermediate402Path: String = localTopicOnePath+"/intermediate-402/"
        val localIntermediate405Path: String = localTopicOnePath+"/intermediate-405/"
        val localIntermediate413Path: String = localTopicOnePath+"/intermediate-413/"
        val localIntermediate549Path: String = localTopicOnePath+"/intermediate-549/"
        val localIntermediate1426Path: String = localTopicOnePath+"/intermediate-1426/"
        val localIntermediate1427Path: String = localTopicOnePath+"/intermediate-1427/"
        val localIntermediate1428Path: String = localTopicOnePath+"/intermediate-1428/"

        val localTopicTwoPath: String = localTestCoursePath+"/topic-two"
        val localBasic406Path: String = localTopicTwoPath+"/basic-406/"
        val localBasic407Path: String = localTopicTwoPath+"/basic-407/"
        val localBasic1423Path: String = localTopicTwoPath+"/basic-1423/"
        val localBasic1424Path: String = localTopicTwoPath+"/basic-1424/"
        val localAdvanced410Path: String = localTopicTwoPath+"/advanced-410/"
        val localAdvanced411Path: String = localTopicTwoPath+"/advanced-411/"
        val localAdvanced415Path: String = localTopicTwoPath+"/advanced-415/"
        val localAdvanced416Path: String = localTopicTwoPath+"/advanced-416/"
        val localIntermediate412Path: String = localTopicTwoPath+"/intermediate-412/"
        val localIntermediate414Path: String = localTopicTwoPath+"/intermediate-414/"
        val localIntermediate417Path: String = localTopicTwoPath+"/intermediate-417/"
        val localIntermediate1425Path: String = localTopicTwoPath+"/intermediate-1425/"

        val localTopicThreePath: String = localTestCoursePath+"/topic-three"
        val localBasic418Path: String = localTopicThreePath+"/basic-418/"
        val localBasic419Path: String = localTopicThreePath+"/basic-419/"
        val localBasic420Path: String = localTopicThreePath+"/basic-420/"
        val localBasic421Path: String = localTopicThreePath+"/basic-421/"
        val localAdvanced422Path: String = localTopicThreePath+"/advanced-422/"
        val localAdvanced423Path: String = localTopicThreePath+"/advanced-423/"
        val localAdvanced427Path: String = localTopicThreePath+"/advanced-427/"
        val localAdvanced428Path: String = localTopicThreePath+"/advanced-428/"
        val localIntermediate424Path: String = localTopicThreePath+"/intermediate-424/"
        val localIntermediate425Path: String = localTopicThreePath+"/intermediate-424/"
        val localIntermediate426Path: String = localTopicThreePath+"/intermediate-426/"
        val localIntermediate429Path: String = localTopicThreePath+"/intermediate-429/"
    }
}